apiVersion: v1
kind: Secret
metadata:
  name: cb-example-auth
type: Opaque
data:
  username: QWRtaW5pc3RyYXRvcg== # Administrator
  password: cGFzc3dvcmQ=         # password
---
apiVersion: couchbase.com/v2
kind: CouchbaseBucket
metadata:
  name: default
---
apiVersion: couchbase.com/v2
kind: CouchbaseCluster
metadata:
  name: cb-example
spec:
  image: registry.connect.redhat.com/couchbase/server:6.6.2-1
  security:
    adminSecret: cb-example-auth
  buckets:
    managed: true
  servers:
  - size: 3
    name: data
    services:
    - data
    serverGroups:
      - eu-west-1a
      - eu-west-1b
      - eu-west-1c
    volumeMounts:
        default: pvc-default
        data: pvc-data
  - size: 2
    name: query_index_ensemble
    services:
    - index
    - query
    serverGroups:
      - eu-west-1b
      - eu-west-1c
    volumeMounts:
        default: pvc-default
        index: pvc-index
  - size: 2
    name: fts_seul
    services:
    - search
    serverGroups:
      - eu-west-1a
      - eu-west-1c
    volumeMounts:
        default: pvc-default
        index: pvc-index
  cluster:
    autoFailoverTimeout: 10s
  volumeClaimTemplates:
    - metadata:
        name: pvc-default
      spec:
        storageClassName: gp2
        resources:
          requests:
            storage: 1Gi
    - metadata:
        name: pvc-data
      spec:
        storageClassName: gp2
        resources:
          requests:
            storage: 20Gi
    - metadata:
        name: pvc-index
      spec:
        storageClassName: gp2
        resources:
          requests:
            storage: 5Gi
