apiVersion: v1
kind: Secret
metadata:
  name: cb-example-auth
type: Opaque
data:
  username: QWRtaW5pc3RyYXRvcg== # Administrator
  password: cGFzc3dvcmQ=         # password
---
apiVersion: couchbase.com/v2
kind: CouchbaseBucket
metadata:
  name: default
---
apiVersion: couchbase.com/v2
kind: CouchbaseCluster
metadata:
  name: cb-example
spec:
  image: registry.connect.redhat.com/couchbase/server:6.6.2-1
  security:
    adminSecret: cb-example-auth
  buckets:
    managed: true
  servers:
  - size 3
    name: data
    services:
    - data
  - size: 2
    name: query_index
    services:
    - index
    - query
  - size 2
    name: fts_seul
    services: 
    - search
  cluster:
    autoFailoverTimeout: 10s
  logging:
    server:
      enabled: true 
      manageConfiguration: true
      configurationName: "fluent-bit-config"
      sidecar:
        image: registry.connect.redhat.com/openshift3/logging-fluentd:3.11
    audit:
      enabled: true 
      garbageCollection:
        sidecar:
          enabled: true     
  monitoring:
    prometheus:
      enabled: true
      image: registry.connect.redhat.com/couchbase/exporter:1.0.5
      resources:
        requests:
          cpu: 100m
          memory: 100Mi
